FROM node as frontend_build
RUN npm install -g express
COPY . /home/node/app
WORKDIR /home/node/app
ENV NODE_OPTIONS=--openssl-legacy-provider
ENV NODE_ENV=production
RUN npm install
RUN npm run build
CMD ["node", "server.js"]